name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: [completed]
    branches: [main]

jobs:
  deploy-to-staging:
    runs-on: ubuntu-22.04
    permissions:
      # Required so we can download artifact from another workflow
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4
      - run: |
          echo ${{ github.event.workflow_run.id}}
          echo ${{ github.event.workflow_run.workflow_id}}

      - name: Download Release Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release
          path: release
          run-id: ${{ github.event.workflow_run.id}}

      - name: Deploy to Staging
        run: |
          echo "Deploying to staging..."
          # Your deployment script here

      - name: Deploy to Staging
        run: |
          git tag -f staging-latest
          git push origin staging-latest

  deploy-to-beta:
    runs-on: ubuntu-22.04
    needs: deploy-to-staging
    permissions:
      # Required so we can download artifact from another workflow
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Download Release Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release
          path: release
          run-id: ${{ github.event.workflow_run.id}}

      - name: Deploy to Beta
        run: |
          echo "Deploying to beta..."
          # Your deployment script here

      - name: Deploy to Beta
        run: |
          git tag -f beta-latest
          git push origin beta-latest

  deploy-to-production:
    runs-on: ubuntu-22.04
    needs: deploy-to-beta
    permissions:
      # Required so we can download artifact from another workflow
      actions: read
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download Release Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release
          path: release
          run-id: ${{ github.event.workflow_run.id}}

      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          # Your deployment script here

      - name: Deploy to Production
        run: |
          git tag -f production-latest
          git push origin production-latest

      - name: Create a pre-Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/**"
          prerelease: true
          generateReleaseNotes: true
          tag: "$(echo release/version_tag.txt)"
