name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  # Run on only on master branch
  build:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine semantic version
        id: release-version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          bump_each_commit: false
          enable_prerelease_mode: false
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"

      - name: Create release folder
        run: |
          mkdir -p release
          mkdir -p release/sourcemaps
          echo "$(echo ${{ steps.release-version.outputs.version_tag }})" > release/version.txt

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release

      - name: Create a pre-Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/**"
          prerelease: true
          generateReleaseNotes: true
          tag: ${{ steps.release-version.outputs.version }}
